classDiagram
  ラリー -- キャラクター
  ラリー -- コート
  ラリー -- ショット
  コート -- コートの種類
  コート -- コートのエリア
  コート -- ネット
  class ラリー{
    キャラクター
    ショット
    コート
  }
  class コート{
    コートの種類
    コート内エリア
    ネット
  }
  class コートの種類{
    <<enum>>
    %%後で列挙
  }
  class キャラクター{
    <<enum>>
    %%後で列挙
  }
  class ショット{
    
  }
  class ショット{
    <<enum>>
    強フラット
    弱フラット
    強トップ
    弱トップ
    強スライス
    弱スライス
    ロブ
    ドロップ
    スライド
    飛びつき
  }